// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SourcePropertyMapperAttributeGenerator.cs" company="consolovers">
//   Copyright (c) daniel bramer 2022 - 2023
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace MagicMap.Generators;

using System;

using Microsoft.CodeAnalysis;

/// <summary>Attribute that identifies property with different names on the left and right object</summary>
internal class PropertyMapperAttributeGenerator
{
   #region Constructors and Destructors

   private PropertyMapperAttributeGenerator(INamedTypeSymbol attributeSymbol)
   {
      AttributeClass = attributeSymbol ?? throw new ArgumentNullException(nameof(attributeSymbol));
   }

   #endregion

   #region Public Properties

   public static string Code { get; } = @"//------------------------------------------------
// <auto-generated>
//     Generated by the MagicMap source generator
// </auto-generated>
//------------------------------------------------
namespace MagicMap 
{
   [global::System.Runtime.CompilerServices.CompilerGenerated]
   [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
   /// <summary>Attribute that can be used mark a method as mapping method for a specific source property</summary>
   internal sealed class PropertyMapperAttribute : global::System.Attribute
   {
      /// <summary>Marks a function as a custom mapping method for the specified property.</summary>
      public PropertyMapperAttribute(global::System.Type targetType, string targetName)
         : this(targetType, targetName, targetName)
      {
      }

      /// <summary>Marks a function as a custom mapping method for the specified property.</summary>
      public PropertyMapperAttribute(global::System.Type targetType, string targetName, string sourceName)
      {
         TargetType = targetType ?? throw new global::System.ArgumentNullException(nameof(targetType));
         TargetName = targetName ?? throw new global::System.ArgumentNullException(nameof(targetName));
         SourceName  = sourceName ?? throw new global::System.ArgumentNullException(nameof(sourceName));
      }

      /// <summary>Gets the type of the target class, the mapper should be used for.</summary>
      public global::System.Type TargetType { get; }

      /// <summary>Gets the name of the property that should be mapped to.</summary>
      public string TargetName { get; }

      /// <summary>Gets the name of the source property that should be mapped from.</summary>
      public string SourceName { get; }
   }
}
";

   #endregion

   #region Properties

   internal static string AttributeName => "MagicMap.PropertyMapperAttribute";

   internal INamedTypeSymbol AttributeClass { get; }

   #endregion

   #region Methods

   internal static PropertyMapperAttributeGenerator FromCompilation(Compilation compilation)
   {
      var attributeType = compilation.GetTypeByMetadataName(AttributeName);
      if (attributeType == null)
         throw new InvalidOperationException($"The source generator should have generated the type {AttributeName} before");

      return new PropertyMapperAttributeGenerator(attributeType);
   }

   #endregion
}