// --------------------------------------------------------------------------------------------------------------------
// <copyright file="TypeFactoryInterfaceGenerator.cs" company="consolovers">
//   Copyright (c) daniel bramer 2022 - 2023
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace MagicMap.Generators;

using System;

using Microsoft.CodeAnalysis;

internal class TypeFactoryInterfaceGenerator
{
   #region Constants and Fields

   private readonly INamedTypeSymbol interfaceSymbol;

   #endregion

   #region Constructors and Destructors

   private TypeFactoryInterfaceGenerator(INamedTypeSymbol interfaceType)
   {
      interfaceSymbol = interfaceType ?? throw new ArgumentNullException(nameof(interfaceType));
   }

   #endregion

   #region Public Properties

   public static string Code { get; } = @"//------------------------------------------------
// <auto-generated>
//     Generated by the MagicMap source generator
// </auto-generated>
//------------------------------------------------
namespace MagicMap 
{
   /// <summary>Interface that can be implemented by a type mapper, to allow/customize the creation of mapping types.</summary>
   [global::System.Runtime.CompilerServices.CompilerGenerated]
   internal interface ITypeFactory<TTarget, TSource>
   {
      /// <summary>Created an instance of the type TTarget, that is used for a mapping.</summary>
      TTarget Create(TSource source);
   }
}
";

   #endregion

   #region Properties

   internal static string Name => "MagicMap.ITypeFactory`2";

   #endregion

   #region Methods

   internal static TypeFactoryInterfaceGenerator FromCompilation(Compilation compilation)
   {
      var attributeType = compilation.GetTypeByMetadataName(Name);
      if (attributeType == null)
         throw new InvalidOperationException($"The source generator should have generated the type {Name} before");

      return new TypeFactoryInterfaceGenerator(attributeType);
   }

   #endregion
}